name       : rnnoise
version    : 0.4.1
release    : 1
source     :
    - https://gitlab.xiph.org/xiph/rnnoise/-/archive/7f449bf8bd3b933891d12c30112268c4090e4d59/rnnoise-7f449bf8bd3b933891d12c30112268c4090e4d59.tar.gz : 05396f221b308099491d9f4838b58a71ba2224a5e4a1c5276de6385abf369131
license    : BSD-3-Clause
component  : multimedia.library
summary    : Recurrent neural network for audio noise reduction
description: |
    RNNoise is a noise suppression library based on a recurrent neural network.
setup      : |
    %autogen
    %configure --enable-static=no
build      : |
    %make
install    : |
    %make_install
